### ISSUE TITLE
SP1 is Slower Than Risc0 Now?

### ISSUE THREAD

**Issue by khandar-william** [succinctlabs/zkvm-perf#14]
[SP1 was announced as faster zkVM than Risc0.](https://blog.succinct.xyz/introducing-sp1/)
Months later, and I tried to revisit SP1 zkVM.

After reading through this zkvm-perf repository, I tried to find what's the latest banchmark numbers of SP1 vs Risc0.

If my understanding is correct, is SP1 now slower than Risc0?

Here's what I gather:
- From [this github action run](https://github.com/succinctlabs/zkvm-perf/actions/runs/11340600781/job/31537304242), i collect the "Print Results" to get the SP1 benchmark
- From [this github action run](https://github.com/succinctlabs/zkvm-perf/actions/runs/11340598704/job/31537298249), i collect the "Print Results" to get the Risc0 benchmark
- I put them side-by-side and i got the following:
![Screenshot from 2024-10-29 10-54-50](https://github.com/user-attachments/assets/f3abb97f-cda9-4bfa-b53b-1aadd3447594)

Focusing on `prove_duration`:
- for loop and fibonacci program, **sp1 is slower than risc0**
- for tendermint dan reth program, sp1 is faster than risc0 

So, are these numbers correct?
I remembered SP1 being much faster than this for generating proof when it was announced.

**Comment by jtguibas** [comment]
SP1's performance is currently tuned for very large programs, since that tends to be what SP1 is used mostly for. As you can see, we perform well on those. On small programs, we currently incur some recursion overhead due to the way we shard small programs into seperate proofs for computation and memory initialization/finalization. This is a simple fix but we haven't gotten around to working on it. We expect it to be fixed in 4.0.0 or an major release to 3.0.0.
